[[constraint]]
  name = "github.com/lxc/lxd"
  branch = "master"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "^1.20.0"

[[constraint]]
  name = "github.com/BaritoLog/go-boilerplate"
  branch = "master"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "^1.0.6"

[[constraint]]
  name = "github.com/golang/mock"
  version = "^1.1.1"

[prune]
  go-tests = true
unused-packages = true